OPENAI_API_KEY = "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"
GOOGLE_API_KEY = "AQ.Ab8RN6LEdqgUT4EF-sK9_Nymq6hoYthEYEcoAMWhZEWdH3JBDw"
ANTHROPIC_API_KEY = "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"
GROQ_API_KEY = "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"
